# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1101, 607)
        Form.setMinimumSize(QtCore.QSize(1101, 607))
        Form.setMaximumSize(QtCore.QSize(1101, 607))
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1101, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(32, 0))
        self.stackedWidget.setStyleSheet("background: #fffdf5;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome = QtWidgets.QWidget()
        self.welcome.setObjectName("welcome")
        self.pushButton = QtWidgets.QPushButton(self.welcome)
        self.pushButton.setGeometry(QtCore.QRect(410, 530, 271, 41))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalFrame = QtWidgets.QFrame(self.welcome)
        self.verticalFrame.setGeometry(QtCore.QRect(350, 100, 391, 251))
        self.verticalFrame.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background: white;\n"
"")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background: white;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.stackedWidget.addWidget(self.welcome)
        self.one_1 = QtWidgets.QWidget()
        self.one_1.setObjectName("one_1")
        self.verticalFrame1 = QtWidgets.QFrame(self.one_1)
        self.verticalFrame1.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame1.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_5.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.one_1)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.formFrame = QtWidgets.QFrame(self.one_1)
        self.formFrame.setGeometry(QtCore.QRect(40, 270, 1001, 241))
        self.formFrame.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.radioButton = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton)
        self.label_8 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_6 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_2.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_2.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.formFrame)
        self.radioButton_3.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_3.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_3)
        self.label_9 = QtWidgets.QLabel(self.one_1)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        self.label_9.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.one_1)
        self.one_2 = QtWidgets.QWidget()
        self.one_2.setObjectName("one_2")
        self.formFrame_2 = QtWidgets.QFrame(self.one_2)
        self.formFrame_2.setGeometry(QtCore.QRect(40, 270, 1001, 241))
        self.formFrame_2.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_2.setObjectName("formFrame_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formFrame_2)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setHorizontalSpacing(7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.formFrame_2)
        self.radioButton_7.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_7.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_7)
        self.label_13 = QtWidgets.QLabel(self.formFrame_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_13)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.label_14 = QtWidgets.QLabel(self.formFrame_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_14)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.label_15 = QtWidgets.QLabel(self.formFrame_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.radioButton_8 = QtWidgets.QRadioButton(self.formFrame_2)
        self.radioButton_8.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_8.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.formFrame_2)
        self.radioButton_9.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_9.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_9)
        self.verticalFrame_2 = QtWidgets.QFrame(self.one_2)
        self.verticalFrame_2.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame_2.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.verticalFrame_2)
        self.label_16.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.one_2)
        self.label_17.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        self.label_17.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.one_2)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.one_2)
        self.multiple_1 = QtWidgets.QWidget()
        self.multiple_1.setObjectName("multiple_1")
        self.verticalFrame2 = QtWidgets.QFrame(self.multiple_1)
        self.verticalFrame2.setGeometry(QtCore.QRect(40, 70, 1001, 101))
        self.verticalFrame2.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.verticalFrame2)
        self.label_18.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.multiple_1)
        self.label_19.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.pushButton_4 = QtWidgets.QPushButton(self.multiple_1)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_4.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.formFrame1 = QtWidgets.QFrame(self.multiple_1)
        self.formFrame1.setGeometry(QtCore.QRect(40, 190, 1001, 321))
        self.formFrame1.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame1.setObjectName("formFrame1")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formFrame1)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setHorizontalSpacing(7)
        self.formLayout_4.setObjectName("formLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.formFrame1)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.label_20 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_20)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formFrame1)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.label_21 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_21)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formFrame1)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.label_22 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_22)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.checkBox_4 = QtWidgets.QCheckBox(self.formFrame1)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_4)
        self.label_23 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_23)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_4.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem7)
        self.checkBox_5 = QtWidgets.QCheckBox(self.formFrame1)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_5)
        self.label_24 = QtWidgets.QLabel(self.formFrame1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.stackedWidget.addWidget(self.multiple_1)
        self.string_1 = QtWidgets.QWidget()
        self.string_1.setObjectName("string_1")
        self.label_25 = QtWidgets.QLabel(self.string_1)
        self.label_25.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalFrame_21 = QtWidgets.QFrame(self.string_1)
        self.verticalFrame_21.setGeometry(QtCore.QRect(330, 340, 421, 101))
        self.verticalFrame_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalFrame_21.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.verticalFrame_21.setObjectName("verticalFrame_21")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_21)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalFrame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(370, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("background: white;\n"
"")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_6.addWidget(self.lineEdit_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalFrame3 = QtWidgets.QFrame(self.string_1)
        self.verticalFrame3.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame3.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame3.setObjectName("verticalFrame3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_26 = QtWidgets.QLabel(self.verticalFrame3)
        self.label_26.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_7.addWidget(self.label_26)
        self.pushButton_5 = QtWidgets.QPushButton(self.string_1)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_5.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.string_1)
        self.one_3 = QtWidgets.QWidget()
        self.one_3.setObjectName("one_3")
        self.formFrame_3 = QtWidgets.QFrame(self.one_3)
        self.formFrame_3.setGeometry(QtCore.QRect(40, 270, 1001, 241))
        self.formFrame_3.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_3.setObjectName("formFrame_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formFrame_3)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setHorizontalSpacing(7)
        self.formLayout_5.setObjectName("formLayout_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.formFrame_3)
        self.radioButton_10.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_10.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_10.setText("")
        self.radioButton_10.setObjectName("radioButton_10")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_10)
        self.label_27 = QtWidgets.QLabel(self.formFrame_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_27)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        self.label_28 = QtWidgets.QLabel(self.formFrame_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_28)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.label_29 = QtWidgets.QLabel(self.formFrame_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_29)
        self.radioButton_11 = QtWidgets.QRadioButton(self.formFrame_3)
        self.radioButton_11.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_11.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_11.setText("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.formFrame_3)
        self.radioButton_12.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_12.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_12.setText("")
        self.radioButton_12.setObjectName("radioButton_12")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_12)
        self.verticalFrame_3 = QtWidgets.QFrame(self.one_3)
        self.verticalFrame_3.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame_3.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_30 = QtWidgets.QLabel(self.verticalFrame_3)
        self.label_30.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_8.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.one_3)
        self.label_31.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        self.label_31.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_6 = QtWidgets.QPushButton(self.one_3)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_6.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.one_3)
        self.string_2 = QtWidgets.QWidget()
        self.string_2.setObjectName("string_2")
        self.verticalFrame_4 = QtWidgets.QFrame(self.string_2)
        self.verticalFrame_4.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame_4.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_32 = QtWidgets.QLabel(self.verticalFrame_4)
        self.label_32.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.verticalFrame_5 = QtWidgets.QFrame(self.string_2)
        self.verticalFrame_5.setGeometry(QtCore.QRect(330, 340, 421, 101))
        self.verticalFrame_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalFrame_5.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(370, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setStyleSheet("background: white;\n"
"")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_10.addWidget(self.lineEdit_6, 0, QtCore.Qt.AlignHCenter)
        self.label_33 = QtWidgets.QLabel(self.string_2)
        self.label_33.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.pushButton_7 = QtWidgets.QPushButton(self.string_2)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_7.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.string_2)
        self.multiple_2 = QtWidgets.QWidget()
        self.multiple_2.setObjectName("multiple_2")
        self.verticalFrame_6 = QtWidgets.QFrame(self.multiple_2)
        self.verticalFrame_6.setGeometry(QtCore.QRect(40, 70, 1001, 101))
        self.verticalFrame_6.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.verticalFrame_6)
        self.label_34.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.formFrame_4 = QtWidgets.QFrame(self.multiple_2)
        self.formFrame_4.setGeometry(QtCore.QRect(40, 190, 1001, 321))
        self.formFrame_4.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_4.setObjectName("formFrame_4")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formFrame_4)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setHorizontalSpacing(7)
        self.formLayout_6.setObjectName("formLayout_6")
        self.checkBox_10 = QtWidgets.QCheckBox(self.formFrame_4)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_10)
        self.label_35 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_35)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        self.checkBox_6 = QtWidgets.QCheckBox(self.formFrame_4)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_6)
        self.label_36 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_36)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem11)
        self.checkBox_7 = QtWidgets.QCheckBox(self.formFrame_4)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_7)
        self.label_37 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_37)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.checkBox_8 = QtWidgets.QCheckBox(self.formFrame_4)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_8)
        self.label_38 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_38)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_6.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem13)
        self.checkBox_9 = QtWidgets.QCheckBox(self.formFrame_4)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_9)
        self.label_39 = QtWidgets.QLabel(self.formFrame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_39)
        self.pushButton_8 = QtWidgets.QPushButton(self.multiple_2)
        self.pushButton_8.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_40 = QtWidgets.QLabel(self.multiple_2)
        self.label_40.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.stackedWidget.addWidget(self.multiple_2)
        self.multiple_3 = QtWidgets.QWidget()
        self.multiple_3.setObjectName("multiple_3")
        self.verticalFrame_7 = QtWidgets.QFrame(self.multiple_3)
        self.verticalFrame_7.setGeometry(QtCore.QRect(40, 70, 1001, 101))
        self.verticalFrame_7.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_41 = QtWidgets.QLabel(self.verticalFrame_7)
        self.label_41.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_12.addWidget(self.label_41)
        self.formFrame_5 = QtWidgets.QFrame(self.multiple_3)
        self.formFrame_5.setGeometry(QtCore.QRect(40, 190, 1001, 321))
        self.formFrame_5.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_5.setObjectName("formFrame_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formFrame_5)
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setHorizontalSpacing(7)
        self.formLayout_7.setObjectName("formLayout_7")
        self.checkBox_15 = QtWidgets.QCheckBox(self.formFrame_5)
        self.checkBox_15.setText("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_15)
        self.label_42 = QtWidgets.QLabel(self.formFrame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_42)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_7.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem14)
        self.checkBox_11 = QtWidgets.QCheckBox(self.formFrame_5)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_11)
        self.label_43 = QtWidgets.QLabel(self.formFrame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_43)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_7.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem15)
        self.checkBox_12 = QtWidgets.QCheckBox(self.formFrame_5)
        self.checkBox_12.setText("")
        self.checkBox_12.setObjectName("checkBox_12")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_12)
        self.label_44 = QtWidgets.QLabel(self.formFrame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_44)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_7.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem16)
        self.checkBox_13 = QtWidgets.QCheckBox(self.formFrame_5)
        self.checkBox_13.setText("")
        self.checkBox_13.setObjectName("checkBox_13")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_13)
        self.label_45 = QtWidgets.QLabel(self.formFrame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_45)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_7.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem17)
        self.checkBox_14 = QtWidgets.QCheckBox(self.formFrame_5)
        self.checkBox_14.setText("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_14)
        self.label_46 = QtWidgets.QLabel(self.formFrame_5)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setWordWrap(True)
        self.label_46.setObjectName("label_46")
        self.formLayout_7.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_46)
        self.pushButton_9 = QtWidgets.QPushButton(self.multiple_3)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_9.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_47 = QtWidgets.QLabel(self.multiple_3)
        self.label_47.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.stackedWidget.addWidget(self.multiple_3)
        self.one_4 = QtWidgets.QWidget()
        self.one_4.setObjectName("one_4")
        self.verticalFrame_8 = QtWidgets.QFrame(self.one_4)
        self.verticalFrame_8.setGeometry(QtCore.QRect(40, 70, 1001, 161))
        self.verticalFrame_8.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_48 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_48.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setWordWrap(True)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_13.addWidget(self.label_48)
        self.pushButton_10 = QtWidgets.QPushButton(self.one_4)
        self.pushButton_10.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_10.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_49 = QtWidgets.QLabel(self.one_4)
        self.label_49.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        self.label_49.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.formFrame_6 = QtWidgets.QFrame(self.one_4)
        self.formFrame_6.setGeometry(QtCore.QRect(40, 270, 1001, 241))
        self.formFrame_6.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_6.setObjectName("formFrame_6")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formFrame_6)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setHorizontalSpacing(7)
        self.formLayout_8.setObjectName("formLayout_8")
        self.radioButton_13 = QtWidgets.QRadioButton(self.formFrame_6)
        self.radioButton_13.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_13.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_13.setText("")
        self.radioButton_13.setObjectName("radioButton_13")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_13)
        self.label_50 = QtWidgets.QLabel(self.formFrame_6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setWordWrap(True)
        self.label_50.setObjectName("label_50")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_50)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_8.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem18)
        self.label_51 = QtWidgets.QLabel(self.formFrame_6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setWordWrap(True)
        self.label_51.setObjectName("label_51")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_51)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_8.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem19)
        self.label_52 = QtWidgets.QLabel(self.formFrame_6)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setWordWrap(True)
        self.label_52.setObjectName("label_52")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_52)
        self.radioButton_14 = QtWidgets.QRadioButton(self.formFrame_6)
        self.radioButton_14.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_14.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_14.setText("")
        self.radioButton_14.setObjectName("radioButton_14")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.formFrame_6)
        self.radioButton_15.setMinimumSize(QtCore.QSize(25, 0))
        self.radioButton_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_15.setStyleSheet("font: 12pt \"Arial\";")
        self.radioButton_15.setText("")
        self.radioButton_15.setObjectName("radioButton_15")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_15)
        self.stackedWidget.addWidget(self.one_4)
        self.multiple_4 = QtWidgets.QWidget()
        self.multiple_4.setObjectName("multiple_4")
        self.formFrame_7 = QtWidgets.QFrame(self.multiple_4)
        self.formFrame_7.setGeometry(QtCore.QRect(40, 190, 1001, 321))
        self.formFrame_7.setStyleSheet("background: #ffeded;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.formFrame_7.setObjectName("formFrame_7")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formFrame_7)
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setHorizontalSpacing(7)
        self.formLayout_9.setObjectName("formLayout_9")
        self.checkBox_20 = QtWidgets.QCheckBox(self.formFrame_7)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_20)
        self.label_53 = QtWidgets.QLabel(self.formFrame_7)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_53)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_9.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem20)
        self.checkBox_16 = QtWidgets.QCheckBox(self.formFrame_7)
        self.checkBox_16.setText("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_16)
        self.label_54 = QtWidgets.QLabel(self.formFrame_7)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_54)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_9.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem21)
        self.checkBox_17 = QtWidgets.QCheckBox(self.formFrame_7)
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_17)
        self.label_55 = QtWidgets.QLabel(self.formFrame_7)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setWordWrap(True)
        self.label_55.setObjectName("label_55")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_55)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_9.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem22)
        self.checkBox_18 = QtWidgets.QCheckBox(self.formFrame_7)
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBox_18)
        self.label_56 = QtWidgets.QLabel(self.formFrame_7)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_56)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_9.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem23)
        self.checkBox_19 = QtWidgets.QCheckBox(self.formFrame_7)
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBox_19)
        self.label_57 = QtWidgets.QLabel(self.formFrame_7)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_57.setFont(font)
        self.label_57.setWordWrap(True)
        self.label_57.setObjectName("label_57")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_57)
        self.pushButton_11 = QtWidgets.QPushButton(self.multiple_4)
        self.pushButton_11.setGeometry(QtCore.QRect(410, 540, 261, 41))
        self.pushButton_11.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_58 = QtWidgets.QLabel(self.multiple_4)
        self.label_58.setGeometry(QtCore.QRect(40, 20, 1001, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalFrame_9 = QtWidgets.QFrame(self.multiple_4)
        self.verticalFrame_9.setGeometry(QtCore.QRect(40, 70, 1001, 101))
        self.verticalFrame_9.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_9.setObjectName("verticalFrame_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalFrame_9)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_59 = QtWidgets.QLabel(self.verticalFrame_9)
        self.label_59.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setWordWrap(True)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_14.addWidget(self.label_59)
        self.stackedWidget.addWidget(self.multiple_4)
        self.password = QtWidgets.QWidget()
        self.password.setObjectName("password")
        self.verticalFrame_10 = QtWidgets.QFrame(self.password)
        self.verticalFrame_10.setGeometry(QtCore.QRect(350, 150, 401, 251))
        self.verticalFrame_10.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_10.setObjectName("verticalFrame_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalFrame_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.verticalFrame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(180, 45))
        self.label_12.setStyleSheet("background: white;\n"
"")
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.verticalFrame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.label_2 = QtWidgets.QLabel(self.verticalFrame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(180, 45))
        self.label_2.setStyleSheet("background: white;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_12 = QtWidgets.QPushButton(self.password)
        self.pushButton_12.setGeometry(QtCore.QRect(420, 540, 261, 41))
        self.pushButton_12.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.stackedWidget.addWidget(self.password)
        self.not_password = QtWidgets.QWidget()
        self.not_password.setObjectName("not_password")
        self.verticalFrame_11 = QtWidgets.QFrame(self.not_password)
        self.verticalFrame_11.setGeometry(QtCore.QRect(350, 120, 401, 251))
        self.verticalFrame_11.setStyleSheet("background: #edfcff;\n"
"border-radius: 20px;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.verticalFrame_11.setObjectName("verticalFrame_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalFrame_11)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_64 = QtWidgets.QLabel(self.verticalFrame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_17.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.verticalFrame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setMinimumSize(QtCore.QSize(180, 45))
        self.label_65.setStyleSheet("background: white;\n"
"")
        self.label_65.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_17.addWidget(self.label_65, 0, QtCore.Qt.AlignHCenter)
        self.label_66 = QtWidgets.QLabel(self.verticalFrame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic,sans-serif")
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_66.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_17.addWidget(self.label_66)
        self.pushButton_13 = QtWidgets.QPushButton(self.not_password)
        self.pushButton_13.setGeometry(QtCore.QRect(420, 540, 261, 41))
        self.pushButton_13.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.stackedWidget.addWidget(self.not_password)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(12)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Начать тест"))
        self.label_3.setText(_translate("Form", "Введите фамилию и имя"))
        self.label_4.setText(_translate("Form", "Введите номер взвода"))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.pushButton_2.setText(_translate("Form", "Ответить"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "Вопрос 1"))
        self.label_13.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "TextLabel"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "Вопрос 2"))
        self.pushButton_3.setText(_translate("Form", "Ответить"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.label_19.setText(_translate("Form", "Вопрос 3"))
        self.pushButton_4.setText(_translate("Form", "Ответить"))
        self.label_20.setText(_translate("Form", "TextLabel"))
        self.label_21.setText(_translate("Form", "TextLabel"))
        self.label_22.setText(_translate("Form", "TextLabel"))
        self.label_23.setText(_translate("Form", "TextLabel"))
        self.label_24.setText(_translate("Form", "TextLabel"))
        self.label_25.setText(_translate("Form", "Вопрос 4"))
        self.label_26.setText(_translate("Form", "TextLabel"))
        self.pushButton_5.setText(_translate("Form", "Ответить"))
        self.label_27.setText(_translate("Form", "TextLabel"))
        self.label_28.setText(_translate("Form", "TextLabel"))
        self.label_29.setText(_translate("Form", "TextLabel"))
        self.label_30.setText(_translate("Form", "TextLabel"))
        self.label_31.setText(_translate("Form", "Вопрос 5"))
        self.pushButton_6.setText(_translate("Form", "Ответить"))
        self.label_32.setText(_translate("Form", "TextLabel"))
        self.label_33.setText(_translate("Form", "Вопрос 6"))
        self.pushButton_7.setText(_translate("Form", "Ответить"))
        self.label_34.setText(_translate("Form", "TextLabel"))
        self.label_35.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "TextLabel"))
        self.label_38.setText(_translate("Form", "TextLabel"))
        self.label_39.setText(_translate("Form", "TextLabel"))
        self.pushButton_8.setText(_translate("Form", "Ответить"))
        self.label_40.setText(_translate("Form", "Вопрос 7"))
        self.label_41.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.label_43.setText(_translate("Form", "TextLabel"))
        self.label_44.setText(_translate("Form", "TextLabel"))
        self.label_45.setText(_translate("Form", "TextLabel"))
        self.label_46.setText(_translate("Form", "TextLabel"))
        self.pushButton_9.setText(_translate("Form", "Ответить"))
        self.label_47.setText(_translate("Form", "Вопрос 8"))
        self.label_48.setText(_translate("Form", "TextLabel"))
        self.pushButton_10.setText(_translate("Form", "Ответить"))
        self.label_49.setText(_translate("Form", "Вопрос 9"))
        self.label_50.setText(_translate("Form", "TextLabel"))
        self.label_51.setText(_translate("Form", "TextLabel"))
        self.label_52.setText(_translate("Form", "TextLabel"))
        self.label_53.setText(_translate("Form", "TextLabel"))
        self.label_54.setText(_translate("Form", "TextLabel"))
        self.label_55.setText(_translate("Form", "TextLabel"))
        self.label_56.setText(_translate("Form", "TextLabel"))
        self.label_57.setText(_translate("Form", "TextLabel"))
        self.pushButton_11.setText(_translate("Form", "Ответить"))
        self.label_58.setText(_translate("Form", "Вопрос 10"))
        self.label_59.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "Вы набрали"))
        self.label_12.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "Ваш пароль"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.pushButton_12.setText(_translate("Form", "Далее"))
        self.label_64.setText(_translate("Form", "Вы набрали"))
        self.label_65.setText(_translate("Form", "TextLabel"))
        self.label_66.setText(_translate("Form", "Вы не набрали проходного балла"))
        self.pushButton_13.setText(_translate("Form", "Закончить"))
