# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_player(object):
    def setupUi(self, interface_player):
        interface_player.setObjectName("interface_player")
        interface_player.resize(931, 745)
        interface_player.setMinimumSize(QtCore.QSize(800, 600))
        interface_player.setStyleSheet("background: #fffdf5;")
        self.centralwidget = QtWidgets.QWidget(interface_player)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(220, 570, 491, 71))
        self.plainTextEdit.setStyleSheet("background: white;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.send_msg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_msg_btn.setGeometry(QtCore.QRect(330, 660, 271, 41))
        self.send_msg_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 79, 751, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(220, 411, 491, 161))
        self.textBrowser.setStyleSheet("background: #edfcff;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.textBrowser.setObjectName("textBrowser")
        interface_player.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface_player)
        self.statusbar.setObjectName("statusbar")
        interface_player.setStatusBar(self.statusbar)

        self.retranslateUi(interface_player)
        QtCore.QMetaObject.connectSlotsByName(interface_player)

    def retranslateUi(self, interface_player):
        _translate = QtCore.QCoreApplication.translate
        interface_player.setWindowTitle(_translate("interface_player", "Project"))
        self.send_msg_btn.setText(_translate("interface_player", "Отправить"))
