# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_player(object):
    def setupUi(self, interface_player):
        interface_player.setObjectName("interface_player")
        interface_player.resize(931, 745)
        interface_player.setMinimumSize(QtCore.QSize(800, 600))
        interface_player.setStyleSheet("background: #fffdf5;")
        self.centralwidget = QtWidgets.QWidget(interface_player)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 761, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_layout.setContentsMargins(20, 20, 20, 20)
        self.main_layout.setObjectName("main_layout")
        self.download_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.download_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.download_btn.setMaximumSize(QtCore.QSize(1231251, 40))
        self.download_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.download_btn.setObjectName("download_btn")
        self.main_layout.addWidget(self.download_btn)
        self.horizontal_med_layout = QtWidgets.QHBoxLayout()
        self.horizontal_med_layout.setObjectName("horizontal_med_layout")
        self.main_layout.addLayout(self.horizontal_med_layout)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(500, 150))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser.setStyleSheet("background: #edfcff;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.textBrowser.setObjectName("textBrowser")
        self.main_layout.addWidget(self.textBrowser)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(500, 70))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.plainTextEdit.setStyleSheet("background: white;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.main_layout.addWidget(self.plainTextEdit)
        self.send_msg_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_msg_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.send_msg_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.send_msg_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.send_msg_btn.setObjectName("send_msg_btn")
        self.main_layout.addWidget(self.send_msg_btn)
        interface_player.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface_player)
        self.statusbar.setObjectName("statusbar")
        interface_player.setStatusBar(self.statusbar)

        self.retranslateUi(interface_player)
        QtCore.QMetaObject.connectSlotsByName(interface_player)

    def retranslateUi(self, interface_player):
        _translate = QtCore.QCoreApplication.translate
        interface_player.setWindowTitle(_translate("interface_player", "Project"))
        self.download_btn.setText(_translate("interface_player", "Загрузить карту"))
        self.send_msg_btn.setText(_translate("interface_player", "Отправить"))
