# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface_admin(object):
    def setupUi(self, interface_admin):
        interface_admin.setObjectName("interface_admin")
        interface_admin.resize(931, 745)
        interface_admin.setMinimumSize(QtCore.QSize(800, 600))
        interface_admin.setStyleSheet("background: #fffdf5;")
        self.centralwidget = QtWidgets.QWidget(interface_admin)
        self.centralwidget.setObjectName("centralwidget")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(620, 20, 201, 41))
        self.send_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.send_btn.setObjectName("send_btn")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(220, 570, 491, 71))
        self.plainTextEdit.setStyleSheet("background: white;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 660, 271, 41))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 79, 751, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(220, 411, 491, 161))
        self.textBrowser.setStyleSheet("background: #edfcff;\n"
"font-size: 12pt;\n"
"font-family: Century Gothic, sans-serif;")
        self.textBrowser.setObjectName("textBrowser")
        self.add_computer_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_computer_btn.setGeometry(QtCore.QRect(0, 140, 41, 31))
        self.add_computer_btn.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.add_computer_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Models/Computer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_computer_btn.setIcon(icon)
        self.add_computer_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_computer_btn.setObjectName("add_computer_btn")
        self.add_router_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_router_btn.setGeometry(QtCore.QRect(0, 170, 41, 31))
        self.add_router_btn.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.add_router_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Models/Router.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_router_btn.setIcon(icon1)
        self.add_router_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_router_btn.setObjectName("add_router_btn")
        self.add_commutator_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_commutator_btn.setGeometry(QtCore.QRect(0, 200, 41, 31))
        self.add_commutator_btn.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.add_commutator_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Models/Commutator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_commutator_btn.setIcon(icon2)
        self.add_commutator_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_commutator_btn.setObjectName("add_commutator_btn")
        self.add_arc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_arc_btn.setGeometry(QtCore.QRect(0, 230, 41, 31))
        self.add_arc_btn.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.add_arc_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Models/Arc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_arc_btn.setIcon(icon3)
        self.add_arc_btn.setIconSize(QtCore.QSize(32, 32))
        self.add_arc_btn.setObjectName("add_arc_btn")
        self.download_btn = QtWidgets.QPushButton(self.centralwidget)
        self.download_btn.setGeometry(QtCore.QRect(330, 20, 201, 41))
        self.download_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.download_btn.setObjectName("download_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(40, 20, 201, 41))
        self.save_btn.setStyleSheet("QPushButton\n"
"{\n"
"    background: #03a9f4;\n"
"    color: #fff;\n"
"    border-radius: 15px;\n"
"    font-size: 12pt;\n"
"    font-family: Century Gothic, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#64bee8;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#03a9f4;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        interface_admin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface_admin)
        self.statusbar.setObjectName("statusbar")
        interface_admin.setStatusBar(self.statusbar)

        self.retranslateUi(interface_admin)
        QtCore.QMetaObject.connectSlotsByName(interface_admin)

    def retranslateUi(self, interface_admin):
        _translate = QtCore.QCoreApplication.translate
        interface_admin.setWindowTitle(_translate("interface_admin", "Project"))
        self.send_btn.setText(_translate("interface_admin", "Отправить карту"))
        self.pushButton_2.setText(_translate("interface_admin", "Отправить"))
        self.download_btn.setText(_translate("interface_admin", "Загрузить карту"))
        self.save_btn.setText(_translate("interface_admin", "Сохранить карту"))
